language: go
services:
    - redis-server
go:
  - 1.4
install: ./scripts/build-setup.sh
script: 
    - ./scripts/build-build.sh
    - ./scripts/test.sh
after_script:
    - go test -v -covermode=count -coverprofile=coverage.out .
    - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
